version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.16
    commands:
      - echo "Downloading dependencies..."
      - go get ./...
  pre_build:
    commands:
      - echo "Building the project..."
      - GOOS=linux go build -o main
      - zip main.zip main
      - echo "Checking if Lambda function exists..."
      - |
        if ! aws lambda get-function --function-name mailservice-lambda > /dev/null 2>&1; then
          echo "Lambda function does not exist, creating..."
          aws lambda create-function --function-name mailservice-lambda --zip-file fileb://main.zip --handler main --runtime go1.x --role arn:aws:iam::818787057865:role/jgn-lambda-exec-role
        fi
  build:
    commands:
      - echo "Rebuilding the project for any changes..."
      - GOOS=linux go build -o main
      - zip main.zip main
  post_build:
    commands:
      - echo "Post-build phase: deploying to AWS Lambda..."
      - aws lambda update-function-code --function-name mailservice-lambda --zip-file fileb://main.zip

artifacts:
  files:
    - main.zip
  discard-paths: yes
