version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.18
    commands:
      - echo "Downloading dependencies..."
      - go get ./...
  pre_build:
    commands:
      - echo "Building the project..."
      - GOOS=linux go build -o main
      - zip main.zip main mailTemplate.html
  build:
    commands:
      - echo "Rebuilding the project with changes..."
      - GOOS=linux go build -o main
      - zip main.zip main mailTemplate.html
  post_build:
    commands:
      - echo "Deploying to AWS Lambda..."
      - aws lambda update-function-code --function-name mailservice-lambda --zip-file fileb://main.zip

artifacts:
  files:
    - main.zip
  discard-paths: yes
