version: 0.2

phases:
  install:
    runtime-versions:
      golang: 1.16
    commands:
      - echo "Downloading dependencies..."
      - go get ./...
  build:
    commands:
      - echo "Rebuilding the project for with changes..."
      - GOOS=linux go build -o main
      - zip main.zip main
  post_build:
    commands:
      - echo "Post-build phase: deploying to AWS Lambda..."
      - aws lambda update-function-code --function-name mailservice-lambda --zip-file fileb://main.zip

artifacts:
  files:
    - main.zip
  discard-paths: yes
